[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-assets"
version = "0.0.1"
description = "금융 자산 데이터 처리 모듈 (캔들스틱, 가격 등)"
requires-python = ">=3.10"
authors = [
    {name = "생선공장", email = "gatesplan@gmail.com"}
]
license = {text = "MIT"}
dependencies = [
    "pandas>=2.0.0",
    "pyarrow>=21.0.0",
    "python-dotenv>=1.0.0",
    "sqlalchemy>=2.0.0",
    "pymysql>=1.0.0",
    "simple-logger"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["financial_assets*"]
exclude = ["logs*", "tests*"]

[project.urls]
Homepage = "https://github.com/gatesplan/python-toolbox"
Repository = "https://github.com/gatesplan/python-toolbox"
